---
title: "PriMERGEry"
---

## Background

With 183 primary schools in Singapore (as of 2019), parents of primary school students may require to ballot during the Primary 1 (P1) Registration Exercise to secure a place in a preferred school. One main criteria that affects a student's priority of admission is his/her residential's distance away from the school of choice. The Home-School Distance category is an important factor that secures a place for the child in the primary school, and thus an available school within the acceptable distance of the family's residential address in turn affects the accessibility to schools in the acceptable area.

With recent mergers and closures of primary schools in the past few years, the government has mentioned about the due to shrinking school cohorts and declining birth rates. In order to visualize the negative effects of closures on the accessibility of schools for some students living in certain residential areas and subzones, using a geographic system would be helpful. As such, our team from SMU began working on this project to conduct geospatial analytics to analyze the possible decreased accessibility for certain families who have children studying in primary schools.

## [Link](https://docs.google.com/document/d/1bIIGOzbnp0Wv_l7WOT4sib5V69wssQCK/edit?usp=sharing&ouid=115568116821271386627&rtpof=true&sd=true) to full report
